http {
  host = localhost
  host = ${?HTTP_HOST}

  port = 8000
  port = ${?HTTP_PORT}

  base-uri = "http://"${http.host}":"${http.port}
  base-uri = ${?BASE_URI}
}

telegram {
  token = ${TELEGRAM_TOKEN}

  owner-id = ${?TELEGRAM_OWNER}

  authorized-group = ${TELEGRAM_AUTH_GROUP}

  api-base-uri = "https://api.telegram.org/"
  api-base-uri = ${?TELEGRAM_API}
}

integration {
  google {
    client-id = ${GOOGLE_CLIENT_ID}
    client-secret = ${GOOGLE_SECRET}
  }

  notifications {
    default-freq = "0 0 * ? * *"
  }
}

db {
  driver = ${DB_DRIVER}
  connection-string = ${DB_URI}
  username = ${DB_USERNAME}
  password = ${DB_PASSWORD}
}
